Added Webots windows error example
NUbots/NUbook pull request #202
Opened 2021-12-04 01:18 UTC by JamieTsang19

2021-12-04 03:09 UTC, LachlanCourt requested changes
If we're not using the image anymore we may as well delete it from the repo

2022-01-14 09:00 UTC, LachlanCourt commented
You might need to run `yarn format` locally to fix this one up :) sometimes NUbook commits done on github are hard to get the formatting right
Do you want to remove the image while you're at it as we won't be using it anymore @JamieTsang19 ?

2022-01-14 09:01 UTC, LachlanCourt requested changes
You might need to run `yarn format` locally to fix this one up :) sometimes NUbook commits done on github are hard to get the formatting right
Do you want to remove the image while you're at it as we won't be using it anymore @JamieTsang19 ?

2022-06-10 23:31 UTC, ysims approved these changes

2022-06-10 23:31 UTC, merged