New TranZorb pn due to EOL part
NUbots/NUbook pull request #208
Opened 2022-01-18 06:54 UTC by tayloryoung6396

2022-01-18 22:16 UTC, LachlanCourt requested changes

2022-01-18 22:16 UTC, LachlanCourt commented on src/book/02-system/04-hardware/01-overview.mdx
> +The servos have been modified to include a [1.5KE18CA TranZorb](https://www.st.com/content/ccc/resource/technical/document/datasheet/03/7a/4e/3b/96/c3/4e/37/CD00000663.pdf/files/CD00000663.pdf/jcr:co
```suggestion
The servos have been modified to include a [1.5KE18CA TranZorb](https://www.st.com/content/ccc/resource/technical/document/datasheet/03/7a/4e/3b/96/c3/4e/37/CD00000663.pdf/files/CD00000663.pdf/jcr:content/translations/en.CD00000663.pdf), formerlly [1N6385 TranZorb](http://www.vishay.com/docs/88356/icte.pdf), connected in parallel to the servo motor.
```

2022-01-19 00:03 UTC, Bidski requested changes

2022-01-19 00:03 UTC, Bidski commented on src/book/02-system/04-hardware/01-overview.mdx
> +The servos have been modified to include a [1.5KE18CA TranZorb](https://www.st.com/content/ccc/resource/technical/document/datasheet/03/7a/4e/3b/96/c3/4e/37/CD00000663.pdf/files/CD00000663.pdf/jcr:co
```suggestion
The servos have been modified to include a [1.5KE18CA TranZorb](https://www.st.com/content/ccc/resource/technical/document/datasheet/03/7a/4e/3b/96/c3/4e/37/CD00000663.pdf/files/CD00000663.pdf/jcr:content/translations/en.CD00000663.pdf), formerly [1N6385 TranZorb](http://www.vishay.com/docs/88356/icte.pdf), connected in parallel to the servo motor.
```

2022-01-19 00:07 UTC, Bidski approved these changes
LGTM

2022-01-26 02:37 UTC, LachlanCourt approved these changes

2022-05-13 22:21 UTC, merged