Adds the 2022 Rules Section for Behaviour
NUbots/NUbook pull request #229
Opened 2022-06-11 07:59 UTC by BryceTuppurainen

As an idea from year-to-year to ensure that the team is aware of the rules and the rule changes that apply for their subsystems that they're working on (in this case behaviour) I've added a little details section to the end of the behaviour subsystem that states what the 2022 rules are specifically regarding penalties.

As they're implemented I can update NUbook to state (and link) where in the codebase each rule is being fulfilled so that anyone looking at this in future can immediately determine which lines to edit and what to do in order to adjust for future rule changes and we can make sure that they're all being covered easily from there.

2022-06-11 08:03 UTC, BryceTuppurainen commented
https://deploy-preview-229--nubook.netlify.app/ <-- Preview

2022-06-11 09:56 UTC, ysims commented
This is in the script tuner section of the page? It would be better to put it in a rules section or play state section.

2022-06-11 23:29 UTC, LachlanCourt commented on src/book/02-system/02-subsystems/06-behaviour.mdx
> +Based on the rules as specified in the [RoboCup Humanoid Rules](https://github.com/RoboCup-Humanoid-TC/Rules) there are some states in the game such as when a penalty occurs in favor of the opposing
```suggestion
Based on the specifications in the [RoboCup Humanoid Rules](https://github.com/RoboCup-Humanoid-TC/Rules) there are some states in the game where the robots need to then act differently to their regular behaviour, for example if the opposing team has been granted a free kick,  we might need to stand still, or move out of the way for the duration of the kick.
```

2022-06-11 23:36 UTC, LachlanCourt requested changes
Please add a new section for this rather than nesting it under script tuner

2022-06-11 23:36 UTC, LachlanCourt commented on src/book/02-system/02-subsystems/06-behaviour.mdx
> +### _All free kicks are taken from the place where the offence occurred, except:_
```suggestion
### All free kicks are taken from the place where the offence occurred, except:
```

2022-06-11 23:36 UTC, LachlanCourt commented on src/book/02-system/02-subsystems/06-behaviour.mdx
> +[In the revision of the rules as per March 24th 2022:](http://humanoid.robocup.org/wp-content/uploads/RC-HL-2022-Rules.pdf)
To match the convention of dates elsewhere in nubook
```suggestion
[In the revision of the rules as per 24th of March 2022:](http://humanoid.robocup.org/wp-content/uploads/RC-HL-2022-Rules.pdf)
```

2022-06-11 23:36 UTC, LachlanCourt commented on src/book/02-system/02-subsystems/06-behaviour.mdx
> +  taken from the nearest point on the penalty area line which runs parallel to the goal line._
```suggestion
- Indirect free kicks to the attacking team for an offence inside the opponent's penalty area, which are taken from the nearest point on the penalty area line which runs parallel to the goal line.
```

2022-06-11 23:36 UTC, LachlanCourt commented on src/book/02-system/02-subsystems/06-behaviour.mdx
> +  from anywhere in that area_
```suggestion
- In the physical competition, where free kicks to the defending team in their goal area may be taken from anywhere in that area
```

2022-06-11 23:36 UTC, LachlanCourt commented on src/book/02-system/02-subsystems/06-behaviour.mdx
> +### _Until the ball is in play all opponents must remain:_
```suggestion
### Until the ball is in play all opponents must remain:
```

2022-06-11 23:36 UTC, LachlanCourt commented on src/book/02-system/02-subsystems/06-behaviour.mdx
> +- _0.75m for KidSize and 1.5m for AdultSize from the ball until it is in play, unless they are on their own goal line between the goalposts_
```suggestion
- 0.75m for KidSize and 1.5m for AdultSize from the ball until it is in play, unless they are on their own goal line between the goalposts
```

2022-06-11 23:36 UTC, LachlanCourt commented on src/book/02-system/02-subsystems/06-behaviour.mdx
> +- _Outside the penalty area for free kicks inside the opponents' penalty area_
```suggestion
- Outside the penalty area for free kicks inside the opponent's penalty area
```

2022-06-13 22:31 UTC, ysims commented on src/book/02-system/02-subsystems/06-behaviour.mdx
> +### All free kicks are taken from the place where the offence occurred, except:
I don't think this should be a heading

2022-06-14 08:20 UTC, LachlanCourt submitted a review, later dismissed

2024-04-17 22:01 UTC, ysims approved these changes

2024-04-17 22:03 UTC, merged