Added documentation for the documentation generator
NUbots/NUbook pull request #83
Opened 2020-12-12 03:28 UTC by ElderNoSpace

Some documentation for the new `./b` documentation generation script.

2020-12-12 03:35 UTC, JosephusPaye requested changes
Some suggestions...

2020-12-12 03:35 UTC, JosephusPaye commented on src/book/02-system/01-foundations/02-build-system.mdx
> +| doc       | Create json documenting each module's reactors                 |
```suggestion
| doc       | Dump documentation of each module's emits and reactions in JSON format                 |
```

2020-12-12 03:35 UTC, JosephusPaye commented on src/book/02-system/01-foundations/02-build-system.mdx
> +The `-m` or `--multiprocess` argument tells the command to use multiprocessing to greatly reduce the processing time, but uses a very large amount of RAM, about 1G per thread.
```suggestion
The `-m` or `--multiprocess` argument tells the command to use multiprocessing to greatly reduce the processing time, but uses a very large amount of RAM, about 1GB per thread.
```

2020-12-12 03:35 UTC, JosephusPaye commented on src/book/02-system/01-foundations/02-build-system.mdx
> +##### Doc
Just spit balling, but would something like `./b extract-reactions` or similar be a good alternative. That way we can keep the `./b doc` to be something else, like extract READMEs and comments from modules?

2020-12-12 03:35 UTC, JosephusPaye commented on src/book/02-system/01-foundations/02-build-system.mdx
> +| doc       | Create json documenting each module's reactors                 |
The rest of the table might need formatting if you commit this suggestion.

2021-01-26 22:05 UTC, KipHamiltons requested changes

2021-01-26 22:44 UTC, JosephusPaye commented on src/book/02-system/01-foundations/02-build-system.mdx
> +
The plan is to eventually extract the documentation, generate the images, and submit a PR to NUbook. Ideally automatically in CI when NUbots code changes. 

The JSON here is custom, and I think Cameron has written something that does the conversion.

2021-01-30 01:16 UTC, ElderNoSpace commented on src/book/02-system/01-foundations/02-build-system.mdx
> +
Argparse auto generates a `-h` argument, I don't think it needs to be explicitly documented. If it should exist it should be general for all b scripts.

2021-01-30 01:18 UTC, Bidski commented
Wait .... The documentation generator doesn't generate its own documentation???? Missed opportunity

2021-02-05 02:29 UTC, ElderNoSpace commented on src/book/02-system/01-foundations/02-build-system.mdx
> +The `extract-reactions` command of `b` generates a JSON file documenting each Module. It lists each reactor, with their on statements and emit statements. The on and emit statements have their locati
How so?

2021-02-05 02:30 UTC, ElderNoSpace commented on src/book/02-system/01-foundations/02-build-system.mdx
> +| extract-reactions | Dump documentation of each module's ons, emits and reactions in JSON format |
How so?

2021-02-05 02:34 UTC, ElderNoSpace commented on src/book/02-system/01-foundations/02-build-system.mdx
> +
@KipHamiltons Have you found any clang api docs? I haven't.
If you need to convert to DOT https://gist.github.com/ElderNoSpace/f0042e99b713601e0589a7692f6bff75
I don't think this tool warrants its own page.

2021-02-05 02:34 UTC, ElderNoSpace commented on src/book/02-system/01-foundations/02-build-system.mdx
> +The `-m` or `--multiprocess` argument tells the command to use multiprocessing to greatly reduce the processing time, but uses a very large amount of RAM, about 1GB per thread.
Readded

2021-02-07 00:37 UTC, KipHamiltons commented on src/book/02-system/01-foundations/02-build-system.mdx
> +
Here is a couple of links which would perhaps be useful? I'll let you be the judge of whether they give good insight into using the python bindings.
https://libclang.readthedocs.io/en/latest/
https://clang.llvm.org/doxygen/group__CINDEX.html
https://eli.thegreenplace.net/2011/07/03/parsing-c-in-python-with-clang

2021-07-01 14:00 UTC, JosephusPaye requested changes

2021-07-01 14:00 UTC, JosephusPaye commented on src/book/02-system/01-foundations/02-build-system.mdx
> +The `extract-documentation` command of `b` generates a JSON file documenting each Module. It lists each reactor, with their on statements and emit statements. The on and emit statements have their lo
```suggestion
The `./b extract-documentation` command generates a JSON file documenting each module. It lists each reactor, with their on statements and emit statements. The on and emit statements have their location in the file and their DSL words also.
```

2025-01-01 02:03 UTC, CMurtagh-LGTM commented
Probably not worth the hassle

2025-01-01 02:03 UTC, closed without merging