Adds fixes for issues that can be fixed with `./b configure`
NUbots/NUbook pull request #97
Opened 2021-02-24 03:49 UTC by KipHamiltons

2021-02-24 06:37 UTC, ElderNoSpace submitted a review, later dismissed
LGTM

2021-02-24 06:53 UTC, JosephusPaye requested changes

2021-02-24 06:53 UTC, JosephusPaye commented on src/book/03-guides/04-general/02-troubleshooting.mdx
> +then, run `./b configure --clean`. This refreshes the docker volumes, removing the offending file.
```suggestion
Run `./b configure --clean`. This refreshes the docker volumes, removing the offending file.
```

2021-02-24 06:53 UTC, JosephusPaye commented on src/book/03-guides/04-general/02-troubleshooting.mdx
> +If you have just added a new file to the codebase, make sure first that it's part of a role. After you have added it to a role, run `./b configure`, and the build system should detect the new file an
```suggestion
If you have just added a new file to the codebase, make sure that it's part of a role. After you have added it to a role, run `./b configure`, and the build system should detect the new file and compile it the next time you run `./b build`.
```

2021-02-26 21:36 UTC, JosephusPaye approved these changes
LGTM

2021-02-26 23:40 UTC, merged